<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/26_matrix3x3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
ar=np.array([
  [[1,1,5,1],
   [1,1,1,9]],
   [[1,3,1,1],
    [1,1,21,1]]
])
print(ar)

[[[ 1  1  5  1]
  [ 1  1  1  9]]

 [[ 1  3  1  1]
  [ 1  1 21  1]]]


In [3]:
print(ar[0][0][2])

5


In [4]:
print(ar[0][1][-1])

9


In [5]:
print(ar[1][0][1])

3


In [6]:
print(ar[1][1][2])

21


In [7]:
print(ar[1,1,2])

21
