<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/main/usingArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
array1=np.array([-1,4,7,9])
print(array1)

[-1  4  7  9]


In [9]:
array2=np.array(range(1,11))
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
tuple_ = (10,11,12,13,14)
array3=np.array(tuple_)
print(array3)

[10 11 12 13 14]


In [11]:
array4=np.array(range(1990,2021,5))
print(array4)

[1990 1995 2000 2005 2010 2015 2020]


In [12]:
array5=np.array(range(2020,1890,-10))
print(array5)

[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]


In [13]:
array6=np.array(100)
print(array6)

100
