<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/main/Array_of_ones_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.ones(10)
print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
B=np.ones((4,4))
print(B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
C=np.ones((3,2),dtype=float)
print(C)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
