<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/main/zerosMat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
B=np.zeros(shape=(2,2))
print(B)

[[0. 0.]
 [0. 0.]]


In [6]:
C=np.zeros(shape=(4,6))
print(C)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
