<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/6_howOrder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
A=np.arange(10,50,5).reshape(-1,1)
print(A)
A=np.array(range(10,50,5)).reshape(-1,1)
print(A)

[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]
[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]


In [3]:
B=np.arange(-50,0,5)
print(B)
B=np.array(range(-50,0,5))
print(B)

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]
[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]


In [5]:
C=np.arange(50,150,2).reshape((5,10))
print(C)
C=np.array(range(50,150,2)).reshape(5,10)
print(C)

[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]
[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]
