<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/14_differentsLinspaces.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array1 = np.arange(1,11)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
array2 = np.linspace(1,50,10)
print(array2)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [5]:
array3=np.array(range(51))
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [6]:
array4=np.logspace(1,10,5)
print(array4)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [7]:
array5=np.diag(range(5,31,5))
print(array5)

[[ 5  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 25  0]
 [ 0  0  0  0  0 30]]
