<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/20_matrixMax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[11,15,33,105],
           [1,140,45,90],
           [67,230,78,99]])
print(A)

[[ 11  15  33 105]
 [  1 140  45  90]
 [ 67 230  78  99]]


In [3]:
print(f'Maximo valor de la matriz: {A.max()}')

Maximo valor del arreglo: 230


In [5]:
print(f'Indice del valor maximo de la matriz: {A.argmax()}')

Indice del valor maximo de la matriz: 9
