<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/21_matrixMinimum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
B=np.array([
  [73,22,20,62,3],
  [68,84,27,59,93],
  [48,52,4,55,50],
  [42,23,63,67,4],
  [44,30,41,31,29]
])
print(B)

[[73 22 20 62  3]
 [68 84 27 59 93]
 [48 52  4 55 50]
 [42 23 63 67  4]
 [44 30 41 31 29]]


In [4]:
print(f'Valor minimo del arreglo: {B.min()}')

Valor minimo del arreglo: 3


In [5]:
print(f'Indice de minimo valor del arreglo: {B.argmin()}')

Indice de minimo valor del arreglo: 4
