<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/23_numberRepeated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([
            [1,3,3,4,5],
            [4,7,11,3,5],
            [1,11,4,4,11]])
print(A)

[[ 1  3  3  4  5]
 [ 4  7 11  3  5]
 [ 1 11  4  4 11]]


In [3]:
B=np.unique(A)
print(B)

[ 1  3  4  5  7 11]
