<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/28_tripleMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A=np.array([[1,2,3],[2,1,-1]])
print(A)

[[ 1  2  3]
 [ 2  1 -1]]


In [4]:
B=np.array([[1,-2,0],[3,0,1],[4,5,6]])
print(B)

[[ 1 -2  0]
 [ 3  0  1]
 [ 4  5  6]]


In [6]:
C=np.array(range(1,10)).reshape(3,3)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
D=np.array([[1],[4],[-3]])
print(D)

[[ 1]
 [ 4]
 [-3]]
