<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/29_createMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
E=np.array(range(1,7)).reshape(6,1)
print(E)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [3]:
F=np.array([1,0,3,-10])
print(F)

[  1   0   3 -10]


In [4]:
G=np.array(range(1,6))
print(G)

[1 2 3 4 5]
