<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/30_Diagonal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.triu(np.arange(1,10).reshape(3,3),k=0)
print(A)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [5]:
B=np.tril(np.arange(1,10).reshape(3,3),k=0)
print(B)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [6]:
C=np.triu(np.arange(100,125).reshape(5,5))
print(C)

[[100 101 102 103 104]
 [  0 106 107 108 109]
 [  0   0 112 113 114]
 [  0   0   0 118 119]
 [  0   0   0   0 124]]
