<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/31_daigonalMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.diag([7,1,-1])
print(A)

[[ 7  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [3]:
B=np.diag([3]*4)
print(B)

[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]


In [4]:
C=np.diag(range(-5,0))
print(C)

[[-5  0  0  0  0]
 [ 0 -4  0  0  0]
 [ 0  0 -3  0  0]
 [ 0  0  0 -2  0]
 [ 0  0  0  0 -1]]
