<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/33_matrixSum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[10,11],[5,1],[-2,4]])
print(A)

[[10 11]
 [ 5  1]
 [-2  4]]


In [3]:
B=np.array([[1,25],[3,4],[0,-10]])
print(B)

[[  1  25]
 [  3   4]
 [  0 -10]]


In [4]:
sum_=A+B
print(sum_)

[[11 36]
 [ 8  5]
 [-2 -6]]
