<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/34_lawMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [13]:
A = np.array([[10,11],[5,1],[-2,4]])
print(A)

[[10 11]
 [ 5  1]
 [-2  4]]


In [3]:
B=np.array([[1,25],[3,4],[0,-10]])
print(B)

[[  1  25]
 [  3   4]
 [  0 -10]]


In [6]:
C=np.array([[7,3],[6,1],[0,0]])
print(C)

[[7 3]
 [6 1]
 [0 0]]


In [7]:
zero=np.zeros(shape=(3,2))
print(zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
print(A+B==B+A)

[[ True  True]
 [ True  True]
 [ True  True]]


In [15]:
print((A+(B+C))==(A+B)+C)

[[ True  True]
 [ True  True]
 [ True  True]]


In [16]:
print(A+zero==A)

[[ True  True]
 [ True  True]
 [ True  True]]
