<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/35_matrixOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,3],[2,1,-1]])
print(A)

[[ 1  2  3]
 [ 2  1 -1]]


In [4]:
B=np.array([[-2,0,1],[3,0,1]])
print(B)

[[-2  0  1]
 [ 3  0  1]]


In [5]:
C=np.array([[-1],[2],[4]])
print(C)

[[-1]
 [ 2]
 [ 4]]


In [6]:
D=np.array([[2,-1]])
print(D)

[[ 2 -1]]


In [8]:
print('A+B',A+B)

A+B [[-1  2  4]
 [ 5  1  0]]


In [9]:
print('A.C',A.dot(C))

A.C [[15]
 [-4]]


In [10]:
print('B.C',B.dot(C))

B.C [[6]
 [1]]


In [11]:
print('C.D',C.dot(D))

C.D [[-2  1]
 [ 4 -2]
 [ 8 -4]]


In [12]:
print('D.A',D.dot(A))

D.A [[0 3 7]]


In [14]:
print('D.B',D.dot(B))

D.B [[-7  0  1]]


In [15]:
print('-A',(-1)*A)

-A [[-1 -2 -3]
 [-2 -1  1]]


In [16]:
print('-D',(-1)*D)

-D [[-2  1]]
