<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/36_compartMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,-3,2],[2,1,-3],[4,-3,-1]])
print (A)

[[ 1 -3  2]
 [ 2  1 -3]
 [ 4 -3 -1]]


In [3]:
B = np.array([[1,4,1,0],[2,1,1,1],[1,-2,1,2]])
print(B)

[[ 1  4  1  0]
 [ 2  1  1  1]
 [ 1 -2  1  2]]


In [4]:
C = np.array([[2,1,-1,-2],[3,-2,-1,-1],[2,-5,-1,0]])
print(C)

[[ 2  1 -1 -2]
 [ 3 -2 -1 -1]
 [ 2 -5 -1  0]]


In [5]:
print(A.dot(B)==A.dot(C))

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
