<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/37_transposeMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,-3,2],[2,1,-3],[4,-3,-1]])
print(A)

[[ 1 -3  2]
 [ 2  1 -3]
 [ 4 -3 -1]]


In [3]:
B = np.array([[1,0,4],[-7,5,5],[25,9,11]])
print(B)

[[ 1  0  4]
 [-7  5  5]
 [25  9 11]]


In [6]:
print(A.T,'Matriz A transpuesta') 

[[ 1  2  4]
 [-3  1 -3]
 [ 2 -3 -1]] Matriz A transpuesta


In [7]:
print(B.transpose(),'Matriz B transpuesta')

[[ 1 -7 25]
 [ 0  5  9]
 [ 4  5 11]] Matriz B transpuesta
