<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/38_determinantMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[5]])
print(A)

[[5]]


In [3]:
B = np.array([[1,2],[3,4]])
print(B)

[[1 2]
 [3 4]]


In [4]:
C = np.array([[-3,-8],[-5,-2]])
print(C)

[[-3 -8]
 [-5 -2]]


In [5]:
D = np.eye(2)
print(D)

[[1. 0.]
 [0. 1.]]


In [7]:
det_A = np.linalg.det(A).round()
print(det_A)

5.0


In [9]:
det_B = np.linalg.det(B).round()
print(det_B)

-2.0


In [10]:
det_C = np.linalg.det(C).round()
print(det_C)

-34.0


In [11]:
det_D = np.linalg.det(D).round()
print(det_D)

1.0
