<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/39_determinatMatrix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A = np.array([[3,1,4],[10,7,5],[1,4,4]])
print(A)

[[ 3  1  4]
 [10  7  5]
 [ 1  4  4]]


In [4]:
B = np.eye(3)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
C = np.diag([5,10,2])
print(C)

[[ 5  0  0]
 [ 0 10  0]
 [ 0  0  2]]


In [6]:
D = np.diag([3,7,11,2])
print(D)

[[ 3  0  0  0]
 [ 0  7  0  0]
 [ 0  0 11  0]
 [ 0  0  0  2]]


In [7]:
E = np.array([[5,0,13,12],[1,-1,25,7],[6,2,1,20],[11,4,0,-9]])
print(E)

[[ 5  0 13 12]
 [ 1 -1 25  7]
 [ 6  2  1 20]
 [11  4  0 -9]]


In [8]:
det_A = np.linalg.det(A).round()
print(det_A)

121.0


In [9]:
det_B = np.linalg.det(B).round()
print(det_B)

1.0


In [10]:
det_C = np.linalg.det(C).round()
print(det_C)

100.0


In [11]:
det_D = np.linalg.det(D).round()
print(det_D)

462.0


In [12]:
det_E = np.linalg.det(E).round()
print(det_E)

7081.0
