<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/41_inverseMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [4]:
B = np.array([[-1,3],[5,4]])
print(B)

[[-1  3]
 [ 5  4]]


In [5]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
B_inverse = np.linalg.inv(B)
print(B_inverse)

[[-0.21052632  0.15789474]
 [ 0.26315789  0.05263158]]
