<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/42_inverseMatrix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A = np.array([[4,-1,2,-2],[3,-1,0,0],[2,3,1,0],[0,7,1,1]])
print(A)

[[ 4 -1  2 -2]
 [ 3 -1  0  0]
 [ 2  3  1  0]
 [ 0  7  1  1]]


In [4]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[ -1.  -1.   4.  -2.]
 [ -3.  -4.  12.  -6.]
 [ 11.  14. -43.  22.]
 [ 10.  14. -41.  21.]]
