<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/43_inverseMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
A = np.diag([7, 8, 11, 2, 4, 5, 1, 3])
print(A)

[[ 7  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  0]
 [ 0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  5  0  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  3]]


In [3]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[0.14285714 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.125      0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.09090909 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.5        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.25       0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.2
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.33333333]]
