<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/44_linerMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[1,-1]])
print(A)

[[ 2  3]
 [ 1 -1]]


In [3]:
B = np.array([[6],[8]])
print(B)

[[6]
 [8]]


In [4]:
solution = np.linalg.solve(A,B)
print(solution)

[[ 6.]
 [-2.]]


In [5]:
A = np.array([[3,1],[1,2]])
print(A)

[[3 1]
 [1 2]]


In [6]:
B = np.array([[9],[8]])
print(B)

[[9]
 [8]]


In [7]:
solution = np.linalg.solve(A,B)
print(solution)

[[2.]
 [3.]]
