<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/45_linearMatrix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,0,3],[2,-4,0],[3,-2,-5]])
print(A)

[[ 1  0  3]
 [ 2 -4  0]
 [ 3 -2 -5]]


In [3]:
B = np.array([[-8],[-4],[26]])
print(B)

[[-8]
 [-4]
 [26]]


In [4]:
solution = np.linalg.solve(A,B)
print(solution)

[[ 4.]
 [ 3.]
 [-4.]]
