<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/46_matrixLinalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1, 1, 1], [1, 1, 1,-1], [1, 1, -1, 1], [1, -1, 1, 1]])
print(A)

[[ 1  1  1  1]
 [ 1  1  1 -1]
 [ 1  1 -1  1]
 [ 1 -1  1  1]]


In [3]:
B = np.array([[0],[4],[-4],[2]])
print(B)

[[ 0]
 [ 4]
 [-4]
 [ 2]]


In [4]:
solution = np.linalg.solve(A,B)
print(solution)

[[ 1.]
 [-1.]
 [ 2.]
 [-2.]]
