<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/47_matrixLinalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
print(A)

[[ 3  2  0]
 [ 1 -1  0]
 [ 0  5  1]]


In [3]:
B = np.array([2, 4, -1])
print (B)

[ 2  4 -1]


In [5]:
solution = np.linalg.solve(A,B)
print(solution)

[ 2. -2.  9.]
