<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/48_matrixTrace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [3]:
B = np.array([[10,0,11],[-7,2,5],[45,78,4]])
print(B)

[[10  0 11]
 [-7  2  5]
 [45 78  4]]


In [4]:
C = np.array([[4,2,11,14],[0,-9,1,3],[-3,4,5,8],[0,1,1,2]])
print(C)

[[ 4  2 11 14]
 [ 0 -9  1  3]
 [-3  4  5  8]
 [ 0  1  1  2]]


In [5]:
A_trace = A.trace()
print(A_trace)

5


In [6]:
B_trace = B.trace()
print(B)

[[10  0 11]
 [-7  2  5]
 [45 78  4]]


In [7]:
C_trace = C.trace()
print(C_trace)

2
