<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/49_matrixRank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[2,-1,3],[1,4,2],[1,-5,1],[4,16,8]])
print(A)

[[ 2 -1  3]
 [ 1  4  2]
 [ 1 -5  1]
 [ 4 16  8]]


In [3]:
A_rank = np.linalg.matrix_rank(A)
print(A_rank)

2
