<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/51_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import random

In [2]:
data = random.normal(size = (4,5))
print(data)

[[ 1.35593577  0.29143854 -0.90431853 -1.52962783  0.45976625]
 [ 1.01304473  0.86273131  0.17012191  1.12435472  1.05656199]
 [ 0.40537629 -0.91123069  0.93488032 -1.2604911  -0.43068352]
 [ 0.15666592 -0.09259715 -1.3520594   2.00377985 -0.32481904]]
