<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/52_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from numpy import random

In [2]:
mean = 10
standard_deviation = 3
print(mean)
print(standard_deviation)

10
3


In [3]:
data = random.normal(loc = mean, 
                     scale = standard_deviation, 
                     size = (20, 5))
print(data)

[[11.86207717  9.01695682 10.37935597 11.49994864  6.564052  ]
 [ 8.72110313  8.38616233 12.2704095   7.39725759 12.57687726]
 [ 7.6759219  12.08021137 11.14493327  9.91469844  4.34739028]
 [ 8.92345662  6.8942049  11.96323449 14.83416672  8.20656172]
 [ 8.24839917 13.6183489  13.99870465 11.96457563 12.95954957]
 [ 3.40099634  6.90340776  4.40793723 13.876427    9.71264997]
 [13.52611217 15.14045832  7.84932299 14.91468124  8.59404094]
 [10.14775481  3.43445708 12.84408969 10.78295393  5.62560597]
 [ 8.79644753  6.11242477  5.9834053  11.55313593 10.32253078]
 [10.36803827  7.21031562 14.31314731  3.95807709  7.20001882]
 [ 9.70951497  8.84946718  6.18568318 14.1112814  10.11162597]
 [ 7.15561352  5.93606337 11.8572411  14.02741446 11.15675461]
 [ 6.53086293 11.3349053  11.67493771  6.14257555 10.03239702]
 [10.58855625  6.89691478 13.50949431  9.14471107 14.72596821]
 [ 7.75689732  9.2231893  11.44107092  8.52320813  8.28432643]
 [13.03024171  8.35811316  6.81800353  3.45810625  8.79

In [4]:
df = pd.DataFrame(data, 
                  columns = list('ABCDE'), 
                  index = range(1, data.shape[0]+1))
print(df)

            A          B          C          D          E
1   11.862077   9.016957  10.379356  11.499949   6.564052
2    8.721103   8.386162  12.270410   7.397258  12.576877
3    7.675922  12.080211  11.144933   9.914698   4.347390
4    8.923457   6.894205  11.963234  14.834167   8.206562
5    8.248399  13.618349  13.998705  11.964576  12.959550
6    3.400996   6.903408   4.407937  13.876427   9.712650
7   13.526112  15.140458   7.849323  14.914681   8.594041
8   10.147755   3.434457  12.844090  10.782954   5.625606
9    8.796448   6.112425   5.983405  11.553136  10.322531
10  10.368038   7.210316  14.313147   3.958077   7.200019
11   9.709515   8.849467   6.185683  14.111281  10.111626
12   7.155614   5.936063  11.857241  14.027414  11.156755
13   6.530863  11.334905  11.674938   6.142576  10.032397
14  10.588556   6.896915  13.509494   9.144711  14.725968
15   7.756897   9.223189  11.441071   8.523208   8.284326
16  13.030242   8.358113   6.818004   3.458106   8.792198
17   6.739512 