<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/56_random3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import random

In [2]:
data = random.uniform(size = (3,3))
print(data)

[[0.57470916 0.4836933  0.60019379]
 [0.84734068 0.65266978 0.45264444]
 [0.04948085 0.9647186  0.59505633]]
