<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/58_random4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.random.randint(low = -1000, high = 3000, size = (30, 5))
print(array)

[[2085 2339 2586 1354 -549]
 [ 689 1929 -409 1721  912]
 [1491  533 2465   31 -292]
 [2183 2859 2002  727 1627]
 [ 276 -462 1180 1203 2315]
 [ 972 1764 1629  868  746]
 [1983  197 2756  804  768]
 [2338  715  320  988 2228]
 [2716 2958 2021 1417 1359]
 [-184 2097 2987 -883 -992]
 [1381  428  212 -368 1477]
 [1252 1514 2652 2094 -224]
 [2855 1053 2677 1820 1736]
 [1333 2655 1686 -171 2953]
 [ 714 -632  -51 1320  706]
 [1940 2606 2454 2530 1888]
 [2526 1426  558 2159  283]
 [ 686 -402  987 2319 2814]
 [2235 -106 2196  114  991]
 [  43  516  491 1518 2065]
 [2214 2283 2891 1605 2540]
 [ 476 -555 1848 -636  505]
 [1614  104 -507 -536 -875]
 [ 396 -751 1625 2453 2131]
 [ 513  236 2248 1481 2838]
 [2711 1857  981 1585 1043]
 [2601 1691 1462 1190 -807]
 [ 985  841 -924 2257 1410]
 [-971  378 1730 -209 1381]
 [2543 1473 -892 1463   80]]
