<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/59_random7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.random.randint(5, size = (30, 5))
print(array)

[[2 1 3 0 2]
 [0 3 2 2 0]
 [4 1 4 2 3]
 [3 1 0 3 3]
 [1 4 3 1 0]
 [4 3 0 2 1]
 [2 2 1 4 1]
 [4 4 3 0 4]
 [2 1 2 4 4]
 [2 4 0 3 4]
 [4 4 4 1 2]
 [3 0 4 0 2]
 [1 2 1 1 0]
 [2 4 3 4 2]
 [1 3 0 0 0]
 [4 4 2 1 0]
 [1 2 0 4 1]
 [3 2 3 1 0]
 [3 3 4 1 2]
 [4 3 4 4 1]
 [0 4 3 3 3]
 [3 3 1 1 1]
 [4 2 3 0 1]
 [2 2 4 0 4]
 [1 1 3 0 2]
 [0 0 4 1 1]
 [2 4 1 0 2]
 [3 0 4 3 2]
 [0 4 2 2 1]
 [0 0 0 2 0]]
