<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/61_arrayNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
from numpy import random
import numpy as np

In [2]:
array = random.rand(10,5)
print(array)

[[0.56934316 0.12689015 0.8890037  0.21468392 0.62260814]
 [0.11862116 0.62469075 0.29932632 0.26747906 0.30891781]
 [0.79959467 0.84576307 0.13576615 0.12367343 0.5568977 ]
 [0.95915631 0.28089886 0.54959401 0.80652221 0.64348281]
 [0.2145513  0.27900815 0.39827805 0.0907152  0.77545249]
 [0.90467029 0.84039385 0.77400965 0.42219065 0.93150737]
 [0.28102889 0.95709487 0.9665102  0.2172451  0.63620274]
 [0.3266996  0.69620074 0.50502873 0.0792655  0.69521874]
 [0.80399709 0.59021155 0.78750138 0.09723867 0.53532078]
 [0.09515551 0.42096228 0.43530794 0.96460603 0.90090247]]


In [7]:
mean = array.mean().round(2)
print(f'Mean: {mean}')

Mean: 0.53


In [8]:
standard_deviation = array.std().round(2)
print(f'Standard deviation: {standard_deviation}')

Standard deviation: 0.29


In [15]:
median = np.median(array).round(2)
print(f'Median: {median}')

Median: 0.55
