<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/64_poisson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from numpy import random
import numpy as np

In [5]:
array = random.poisson(lam = 5, size = (50, 3))
print(array)

[[ 7  5  3]
 [ 6  7  4]
 [ 3  5  2]
 [ 4  6  5]
 [ 9  3  7]
 [ 2  2  2]
 [ 5  9  1]
 [ 8  8  4]
 [ 4  5  5]
 [ 9  3  7]
 [ 3  6 11]
 [ 7  4  1]
 [ 5  3  4]
 [ 3  5  8]
 [ 0  2  7]
 [ 1  6  6]
 [ 5  6  5]
 [ 4  3  3]
 [ 5  4  6]
 [ 7  9  3]
 [ 2  4  4]
 [ 2  2  5]
 [ 4  6  5]
 [ 4  8  5]
 [ 4  3  3]
 [ 6  7  4]
 [ 6  4  5]
 [ 5  4  8]
 [ 2  2  5]
 [ 5  2  6]
 [ 6  5 10]
 [ 4  3  4]
 [ 2  0  2]
 [ 5  2  5]
 [ 5  8  4]
 [ 7  4  5]
 [13  0  6]
 [ 4  6  5]
 [ 2  2  2]
 [ 5  6  6]
 [ 7  5  1]
 [ 1  5  6]
 [ 5  2  5]
 [ 4  6  7]
 [ 4  3  3]
 [ 4  6  7]
 [ 3  5  5]
 [ 2  8  9]
 [ 8  3  4]
 [ 4  3  3]]
