<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/7_shapeVsOnes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
A=np.full(shape=(10),fill_value=5,dtype=float)
print(A)
A=5*np.ones(10)
print(A)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
B=np.full(shape=(4,4),fill_value=-5,dtype=float)
print(B)
B=(-5)*np.ones(shape=(4,4))
print(B)

[[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]
[[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]


In [8]:
C=np.full(shape=(3,3),fill_value=3,dtype=int)
print(C)
C=3*np.ones(shape=(3,3),dtype=int)
print(C)

[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [9]:
D=np.full(shape=(10,10),fill_value=50,dtype=int)
print(D)
D=50*np.ones(shape=(10,10),dtype=int)
print(D)

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]
[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]
