<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/89_dataFrame10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.uniform(low = 0, high = 5, size = (100,5))
print(data)

[[3.34774607 3.44705256 1.8044024  2.3644124  2.72528771]
 [2.22437353 0.81412404 1.81758966 1.23035172 4.41708924]
 [2.96947193 3.27848435 4.46757784 0.56945823 4.76996183]
 [0.92572578 1.31723338 3.62357189 4.48343847 0.0826582 ]
 [1.74637673 1.94776089 1.86982103 4.16350367 0.7751081 ]
 [0.95118325 3.78624632 2.33900267 4.54883605 3.96193861]
 [0.94544154 3.59570336 4.97548841 4.95116969 3.67365181]
 [2.13380036 3.0937219  3.17565407 1.61911061 1.85333344]
 [1.8120309  0.22845252 0.0888407  3.64256665 1.67433896]
 [0.43422627 3.60032913 3.07247077 2.07696226 1.18140907]
 [1.41845031 1.17744407 4.21846536 2.79638908 1.62713558]
 [1.57991782 3.87858463 1.29903283 4.02847296 2.523197  ]
 [0.28455658 1.77254532 1.30129832 1.23081458 4.05317699]
 [2.80535157 4.9101563  2.39488261 0.84224893 2.96118963]
 [3.40263232 4.87608169 0.61845771 3.49346637 1.14245897]
 [2.2205643  3.97467077 1.03279054 2.91847979 0.5093751 ]
 [0.19440295 1.76061594 1.34563016 4.31468208 4.27814285]
 [0.22443032 3

In [3]:
df = pd.DataFrame(data, 
                  index = range(1,data.shape[0]+1), 
                  columns = list('ABCDE'))
 
print(f'Number of lines: {df.shape[0]}')
print(f'Number of columns: {df.shape[1]}')
print(f'Shape: {df.shape}')
print(f'The total number of elements: {df.size}')
print(f'Number of dimensions: {df.ndim}')
print('-'*100)
print(f'Dataset information:')
print(df.info())
print('-'*100)
print(f'Dtype of each column: \n{df.dtypes}')
print('-'*100)
print(f'Descriptive statistics: \n{df.describe()}')

Number of lines: 100
Number of columns: 5
Shape: (100, 5)
The total number of elements: 500
Number of dimensions: 2
----------------------------------------------------------------------------------------------------
Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 1 to 100
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       100 non-null    float64
 1   B       100 non-null    float64
 2   C       100 non-null    float64
 3   D       100 non-null    float64
 4   E       100 non-null    float64
dtypes: float64(5)
memory usage: 4.0 KB
None
----------------------------------------------------------------------------------------------------
Dtype of each column: 
A    float64
B    float64
C    float64
D    float64
E    float64
dtype: object
----------------------------------------------------------------------------------------------------
Descriptive statistics: 
                A        