<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/91_randomNormal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
array = np.random.normal(10, 0.5, (10,10)).round(1)
print(array)

[[ 9.  10.  10.6 10.7  9.6  9.4 10.   8.4 10.2 10.4]
 [10.   9.6 10.6 10.7 10.8 10.6 10.6 10.2 10.2  9.7]
 [ 9.7 10.2 10.1  9.6  9.4 10.1 10.   9.9 10.3 10.2]
 [ 9.3  9.7 10.1  9.8  9.9 10.3 10.4 10.2  9.8  9.5]
 [10.2  9.7 10.5 10.1  9.5  9.5  9.9  9.4 10.9 10.5]
 [10.5 10.1 10.3  9.7 10.5 10.9  9.3 10.2 10.3 10.7]
 [ 9.9 10.2  8.7  9.5 10.1 10.4  9.8 10.2 10.4 10.1]
 [ 9.2  9.9 10.1  9.7  9.7  9.7 10.4 10.3  9.6 10.4]
 [10.2 10.4 10.4 10.  10.2 10.4  9.6 10.1 10.9  9.9]
 [10.3  9.7  8.5 10.3 10.   9.7  9.8  9.4 10.2 10.1]]


In [3]:
col = [chr(64+i) for i in range(1, array.shape[1]+1)]  #column
print(col)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']


In [4]:
index = [chr(64+i)+str(i) for i in range(1,array.shape[0]+1)]
print(index)

['A1', 'B2', 'C3', 'D4', 'E5', 'F6', 'G7', 'H8', 'I9', 'J10']


In [5]:
df = pd.DataFrame(data = array, columns = col, index= index)
print(df)

        A     B     C     D     E     F     G     H     I     J
A1    9.0  10.0  10.6  10.7   9.6   9.4  10.0   8.4  10.2  10.4
B2   10.0   9.6  10.6  10.7  10.8  10.6  10.6  10.2  10.2   9.7
C3    9.7  10.2  10.1   9.6   9.4  10.1  10.0   9.9  10.3  10.2
D4    9.3   9.7  10.1   9.8   9.9  10.3  10.4  10.2   9.8   9.5
E5   10.2   9.7  10.5  10.1   9.5   9.5   9.9   9.4  10.9  10.5
F6   10.5  10.1  10.3   9.7  10.5  10.9   9.3  10.2  10.3  10.7
G7    9.9  10.2   8.7   9.5  10.1  10.4   9.8  10.2  10.4  10.1
H8    9.2   9.9  10.1   9.7   9.7   9.7  10.4  10.3   9.6  10.4
I9   10.2  10.4  10.4  10.0  10.2  10.4   9.6  10.1  10.9   9.9
J10  10.3   9.7   8.5  10.3  10.0   9.7   9.8   9.4  10.2  10.1
