<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/98_dataFrameRandom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(77)
data = np.random.randint(1,50,16).reshape((4,4))
print(data)

[[24 32 21 21]
 [44 38 25 32]
 [33 40 45 20]
 [33 37 37 48]]


In [3]:
df = pd.DataFrame(data, 
                columns = ['A', 'B', 'C', 'D'],
                index = ['i', 'j', 'k', 'w'])
print(df)

    A   B   C   D
i  24  32  21  21
j  44  38  25  32
k  33  40  45  20
w  33  37  37  48


In [4]:
df.drop(['k', 'j'], inplace = True)
df.drop(['A', 'D'], axis = 1, inplace = True)
print(df)

    B   C
i  32  21
w  37  37
